export type { GlobalConfig } from './config.js'
export { configure, getConfig } from './config.js'
export { createLogger, LogPalette } from './logger.js'
export { disableAll, enableAll, getAllLoggers, getLogger, setGlobalLevel } from './registry.js'
export type { Logger, LoggerOptions, LogLevel } from './types.js'
